name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0,3,12,15 * * *"

jobs:
  "Push_GitHub-Pkg":
    container: archlinux
    runs-on: ubuntu-20.04
    steps:
    - name: Env
      run: |
        pacman -Syyuu --needed --noconfirm base base-devel git docker docker-compose
        git clone https://aur.archlinux.org/buildkit.git && cd buildkit
        sed -i -e /exit\ \$E_ROOT/d /bin/makepkg
        yes|makepkg -si
        conf='https://gist.github.com/koumaza/831c0b33d05b1ffd28826700541bbc8a/raw/01e44584307eff610b37bf04df3314db0b37a974/config.json'
        curl -Ls $conf > ~/.docker/config.json
        
    - uses: actions/checkout@v2
    - name: Push to GitHub Actions
      env:
        DOCKER_BUILDKIT: 1
        BUILDKIT_INLINE_CACHE: 1
        DOCKER_NAME: docker_archlinux
      run: |
        export GITHUB_DOCKER_REPO=$(printf $GITHUB_REPOSITORY|sed -e 's/^.*\///')
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker buildx build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        else
          docker buildx build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        fi
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        else
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        fi
  "Push_Docker-Hub":
    container: archlinux
    runs-on: ubuntu-20.04
    steps:
    - name: Env
      run: |
        pacman -Syyuu --needed --noconfirm base base-devel git docker docker-compose
        git clone https://aur.archlinux.org/buildkit.git && cd buildkit
        sed -i -e /exit\ \$E_ROOT/d /bin/makepkg
        yes|makepkg -si
        conf='https://gist.github.com/koumaza/831c0b33d05b1ffd28826700541bbc8a/raw/01e44584307eff610b37bf04df3314db0b37a974/config.json'
        curl -Ls $conf > ~/.docker/config.json
        
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      env:
        DOCKER_BUILDKIT: 1
        BUILDKIT_INLINE_CACHE: 1
        DOCKER_NAME: archlinux
        DOCKER_REPO: archlinux
        DOCKER_PROVIDER: registry.hub.docker.com
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_HUB: 1
      run: |
        export GITHUB_DOCKER_REPO=$(printf $GITHUB_REPOSITORY|sed -e 's/^.*\///')
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker buildx build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        else
          docker buildx build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        fi
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        else
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        fi
