name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0,3,12,15 * * *"

jobs:
  "Push_GitHub-Pkg":
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Push to GitHub Actions
      env:
        DOCKER_NAME: docker_archlinux
      run: |
        export GITHUB_DOCKER_REPO=$(printf $GITHUB_REPOSITORY|sed -e 's/^.*\///')
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        else
          docker build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        fi
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        else
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        fi
  "Push_Docker-Hub":
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      env:
        DOCKER_NAME: archlinux
        DOCKER_REPO: archlinux
        DOCKER_PROVIDER: registry.hub.docker.com
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_HUB: 1
      run: |
        export GITHUB_DOCKER_REPO=$(printf $GITHUB_REPOSITORY|sed -e 's/^.*\///')
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        else
          docker build -t ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest} ${DOCKERFILE_PATH:-.}
        fi
        echo ${DOCKER_PASSWORD:-${{ secrets.GITHUB_TOKEN }}} | docker login https://${DOCKER_PROVIDER:-docker.pkg.github.com} -u ${DOCKER_USERNAME:-${{ github.actor }}} --password-stdin
        if [ $DOCKER_HUB = 1 ]; then
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        else
          docker push   ${DOCKER_PROVIDER:-docker.pkg.github.com}/${DOCKER_USERNAME:-${{ github.actor }}}/${DOCKER_REPO:-${GITHUB_DOCKER_REPO}}/${DOCKER_NAME}:${DOCKER_TAG:-latest}
        fi
